employer/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.employer_list, name='employer_list'),
    path('single/', views.employer_single, name='employer_single'),
    path('profile/', views.profile, name='employer_profile'),
    path('profile/edit-main', views.profile_main, name='employer_profile_main'),
    path('profile/edit-contact', views.profile_contact, name='employer_profile_contact'),
    path('jobs/', views.jobs, name='employer_jobs'),
    path('resume/', views.resume, name='employer_resume'),
]

employment_office/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employers/', include('employer.urls')),
    path('candidates/', include('candidate.urls')),
    path('', include('dictionary.urls')),
]

urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

dictionary/forms.py
import uuid

from django import forms
from django.contrib.auth.models import Group
from django.core.exceptions import ValidationError

from dictionary.models import User

USER_TYPE = (
    ('Candidate', 'Кандидат'),
    ('Employer', 'Работодатель')
)


class RegistrationForm(forms.Form):
    first_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'placeholder': 'Имя'}))
    last_name = forms.CharField(max_length=50, required=True, widget=forms.TextInput(attrs={'placeholder': 'Фамилия'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Электронная почта', 'type': 'email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': '**************'}, render_value=True))
    user_type = forms.ChoiceField(choices=USER_TYPE, required=True)
    phone = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'placeholder': 'Телефон'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise ValidationError("Пользователь с таким Email уже зарегистрирован")
        return email

    def register_user(self):
        form_data = self.cleaned_data
        user = User.objects.create_user(
            uuid.uuid4().hex, form_data['email'], form_data['password'],
            first_name=form_data['first_name'], last_name=form_data['last_name'])

        if user is not None:
            print(form_data['user_type'])
            group = Group.objects.get(name=form_data['user_type'])
            group.user_set.add(user)
            user.save()
        else:
            raise ValidationError("Ошибка регистрации. Повторите попытку позже или свяжитесь с администратором")

        return user


class ResetPasswordForm(forms.Form):
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '**************'}, render_value=True))
    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '**************'}, render_value=True))
    new_password_confirm = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': '**************'}, render_value=True))

    def clean(self):
        form_data = self.cleaned_data
        if form_data['new_password'] != form_data['new_password_confirm']:
            self._errors["new_password"] = ["Пароли должны совпадать"]  # Will raise a error message
            del form_data['new_password']
        return form_data

    def reset(self, user):
        form_data = self.cleaned_data
        user.set_password(form_data['new_password'])


class LoginForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'Электронная почта'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': '**************'}, render_value=True))
    remember_me = forms.BooleanField(required=False)

    def clean_email(self):
        data = self.cleaned_data['email']
        if not User.objects.filter(email=data).exists():
            raise ValidationError('Такая электронная почта не зарегестрирована')

templates/fragments/login_fields.html
{{ login_form.email.errors }}
<div class="cfield">
    {{ login_form.email }}
    <i class="la la-envelope-o"></i>
</div>
{{ login_form.password.errors }}
<div class="cfield">
    {{ login_form.password }}
    <i class="la la-key"></i>
</div>
<p class="remember-label">
    {{ login_form.remember_me }}<label for="remember_me">Запомнить меня</label>
</p>
<input hidden value="{{ next }}" name="next">
<a href="#" title="">Забыли пароль?</a>

templates/fragments/nav_menu.html
{% load static %}
{% load user_tags %}
<div class="container">
    <div class="btn-extars">
        {% if not user.is_authenticated %}
            <ul class="account-btns">
                <li class="signup-popup"><a title=""><i class="la la-key"></i>Регистрация</a></li>
                <li class="signin-popup"><a title=""><i class="la la-external-link-square"></i>Войти</a>
                </li>
            </ul>
        {% else %}
            {% if user|has_group:'Employer' %}
                <a href="/job/new/" title="" class="post-job-btn" style="margin-right: 15px"><i class="la la-plus"></i>Добавить
                    вакансию</a>
                <div class="btns-profiles-sec">
                                <span><img src="{% static 'images/resource/profile.jpg' %}" alt=""/> {{ user|credentials }} <i
                                        class="la la-angle-down"></i></span>
                    {% include 'fragments/employer_tree_widget.html' %}
                </div>
            {% else %}
                <div class="my-profiles-sec">
                                    <span>{{ user.first_name|title }} {{ user.last_name|upper }} <i
                                            class="la la-bars"></i></span>
                </div>

            {% endif %}
        {% endif %}
    </div>
    <nav>
        {% include 'fragments/nav_menu_items.html' %}
    </nav>
</div>

templates/fragments/nav_menu_items.html
{% load user_tags %}
<ul>
    <li class="menu-item">
        <a href="/" title="">Home</a>
    </li>
    <li class="menu-item-has-children">
        <a href="/employers/" title="">Работодатели</a>
        <ul>
            <li><a href="/employers/" title="">Список работодателей</a></li>

            {% if user|has_group:'Employer' %}
                <li class="menu-item-has-children">
                <a href="#" title="">Employer Dashboard</a>
                {% include 'fragments/employer_tree_widget.html' %}
            {% endif %}
            </li>
        </ul>

    </li>
    <li class="menu-item-has-children">
        <a href="/candidates/" title="">Кандидаты</a>
        <ul>
            <li><a href="/candidates/" title="">Список кандидатов</a></li>
            {% if user|has_group:'Candidate' %}
                <li class="menu-item-has-children">
                <a href="#" title="">Candidates Dashboard</a>
                {% include 'fragments/candidate_tree_widget.html' %}
            {% endif %}
            </li>
        </ul>

    </li>
    <li class="menu-item">
        <a href="/job/" title="">Вакансии</a>
    </li>
    <li class="menu-item">
        <a href="/about/" title="">О нас</a>
    </li>
</ul>

templates/fragments/profile_sidebar.html
{% load user_tags %}
<div class="profile-sidebar">
    <span class="close-profile"><i class="la la-close"></i></span>
    <div class="can-detail-s">
        <div class="cst"><img src="images/resource/es1.jpg" alt=""/></div>
        <h3>{{ user.first_name|title }} {{ user.last_name|upper }}</h3>
        <span><i>UX / UI Designer</i> at Atract Solutions</span>
        <p><a href="" class="__cf_email__">{{ user.email }}</a></p>
        <p>Member Since, {{ user.date_joined|date:'Y' }}</p>
        <p><i class="la la-map-marker"></i>Istanbul / Turkey</p>
    </div>
    <div class="tree_widget-sec">
        {% if user|has_group:'Employer' %}
            {% include 'fragments/employer_tree_widget.html' %}
        {% else %}
            {% include 'fragments/candidate_tree_widget.html' %}
        {% endif %}
    </div>
</div><!-- Profile Sidebar -->

templates/fragments/registration_fields.html
{{ reg_form.first_name.errors }}
<div class="cfield">
    {{ reg_form.first_name }}
    <i class="la la-user"></i>
</div>
{{ reg_form.last_name.errors }}
<div class="cfield">
    {{ reg_form.last_name }}
    <i class="la la-user"></i>
</div>
{{ reg_form.password.errors }}
<div class="cfield">
    {{ reg_form.password }}
    <i class="la la-key"></i>
</div>
{{ reg_form.email.errors }}
<div class="cfield">
    {{ reg_form.email }}
    <i class="la la-envelope-o"></i>
</div>
{{ reg_form.phone.errors }}
<div class="cfield">
    {{ reg_form.phone }}
    <i class="la la-phone"></i>
</div>
<select name="user_type" id="id_user_type" hidden>
    <option value="Candidate"></option>
    <option value="Employer"></option>
</select>
{{ reg_form.user_type.errors }}